[package]
name = "tree-builder"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
trybuild = { version = "1.0.80", features = ["diff"] }

[dependencies]
tree-builder-macro = {path = "./tree-builder-macro"}
nom = "7.1.3"
